#PARA UTILIZAR ESSES ENDPOINTS É NECESSÁRIO INSTALAR A EXTENSÃO DO VSCODE "REST CLIENT"
###

GET http://localhost:3333/Usuario

###

POST http://localhost:3333/Usuario
Content-Type: application/json

{
    "email": "usuarioteste@hotmail.com",
    "senha": "senhateste123",
    
}

###

PUT http://localhost:3333/Usuario/id
Content-Type: application/json

{
    "email": "testedeusuario@gmail.com",
    "senha": "testeparasenha456",
    
}

###

DELETE http://localhost:3333/Usuario/id

###


GET http://localhost:3333/Reserva

###


POST http://localhost:3333/Reserva

Content-Type: application/json

{
    "dataInicio": "2025-02-12",
    "dataFim": "2025-02-16",
    "quartoReserva": "Domo",

    
}

###

POST http://localhost:3333/Reserva/id

Content-Type: application/json

{
    "dataInicio": "2026-03-22",
    "dataFim": "2026-03-26",
    "quartoReserva": "Cabana",

    
}

###

DELETE http://localhost:3333/Reserva/id

###